name: Build Full DB

on:
  workflow_dispatch:

jobs:
  crawl-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Cache crawler state
        uses: actions/cache@v5
        with:
          path: |
            build/processed.txt
            build/failed.txt
            build/missing_verse_number.txt
          key: crawler-state-${{ hashFiles('tools/crawler/**') }}
          restore-keys: |
            crawler-state-

      - name: Run
        run: |
          make crawler-all-urls
          make tsv
          make import-db
          make crawl-lectionary CALENDAR_URLS="https://raw.githubusercontent.com/nqminhuit/liturgical-calendar/refs/heads/master/resources/liturgical-calendar-2023.json,https://raw.githubusercontent.com/nqminhuit/liturgical-calendar/refs/heads/master/resources/liturgical-calendar-2024.json,https://raw.githubusercontent.com/nqminhuit/liturgical-calendar/refs/heads/master/resources/liturgical-calendar-2025.json,https://raw.githubusercontent.com/nqminhuit/liturgical-calendar/refs/heads/master/resources/liturgical-calendar-2026.json"

      - name: Upload DB artifacts
        uses: actions/upload-artifact@v7
        with:
          path: resources/bible.db
          if-no-files-found: error
          archive: false
